# Generated by Django 4.2.6 on 2023-10-31 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_event_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='sports',
        ),
    ]
