# Generated by Django 4.2.6 on 2023-11-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0008_comment_like_remove_reservation_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='total_dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
