# Generated by Django 4.2.6 on 2023-11-01 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0011_remove_event_total_dislikes_remove_event_total_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dislike',
            name='is_dislike',
        ),
        migrations.RemoveField(
            model_name='like',
            name='is_like',
        ),
    ]
